# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  postman_test:
    name: Postman Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      id: checkout
      uses: actions/checkout@master

    - name: Newman - run collection with postbot scripts
      uses: matt-ball/newman-action@master
      with:
        collection: collection/fakestore.postman_collection.json
        environment: enviroment/FakeStoreAPI.postman_environment.json
